### ISSUE TITLE
2.0.5版本的文字没居中

### ISSUE THREAD

**Issue by SekiBetu** [mengzonefire/rapid-upload-userscript#1]
![image](https://user-images.githubusercontent.com/38283893/131705107-98b4e464-767a-490e-a9b8-63d568a9706a.png)

**Comment by mengzonefire** [comment]
是百度前端更新样式了,  我改一下

**Comment by mengzonefire** [comment]
已提交修复 2.0.6: 1ed3a59fc398c96eea96148883bf78fcbdd8a2fa
脚本页同步更新
