### ISSUE TITLE
准备用VuePress搭建一个指南页面

### ISSUE THREAD

**Issue by XTsat** [mengzonefire/rapid-upload-userscript#10]
作者你好，我非常喜欢这个脚本，我看到你的教程美化页面样式还没有完成，我可以用VuePress来搭建一个教程网站，当然也会为我自己做一些有限度的引流（标题栏关于我的其他内容）

大概样式类似于https://xtsat.github.io/SteamTools-Guide/

你也可以进行修改 ~~（其实是我不一定能及时更新~~

这里问一下作者的文档新页面完成度怎么样了，还有我能不能做这个文档（我准备直接使用脚本GitHub文档分流进行改动重新分类）

**Comment by mengzonefire** [comment]
教程页已经不打算美化了, 因为篇幅非常有限, 基本不会有新内容加进去了, 目前属于摆烂能看就行

你可以随意使用那个markdown版本的文档, 不过我脚本内文档页目前并不打算去动

**Comment by XTsat** [comment]
我是否需要沿用GNU General Public License v3.0协议

**Comment by mengzonefire** [comment]
> 我是否需要沿用GNU General Public License v3.0协议

文档部分的话我认为不属于代码, 默认就当作CC协议吧, 随意使用

**Comment by XTsat** [comment]
暂时先做成这样了，之后我再慢慢美化排版

https://xtsat.github.io/rapid-upload-userscript-doc/

**Comment by mengzonefire** [comment]
> 暂时先做成这样了，之后我再慢慢美化排版
> 
> https://xtsat.github.io/rapid-upload-userscript-doc/

十分感谢, 这样确实人性化很多, 我收回前言, 完成后通知一声, 我引用到脚本内.

**Comment by XTsat** [comment]
~~主体已经放进去了~~还有个主页没放进去，我后续准备重新排版目录结构，再新增一个脚本更新日志和安装按钮，不过文档正文的更新日志我都删了

**Comment by XTsat** [comment]
现在应该基本完工了

**Comment by XTsat** [comment]
我这个是挂在GitHub page上的，有些人应该访问有困难

**Comment by mengzonefire** [comment]
> 我这个是挂在GitHub page上的，有些人应该访问有困难

这个冇问题. 弄好之后我会同步部署到我朋友的国内机器上(mengzonefire.code.misakanet.cn)

**Comment by mengzonefire** [comment]
部署完成: https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc-v2

脚本下个版本将引用v2版的文档

感谢你的付出

**Comment by XTsat** [comment]
> 部署完成: https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc-v2
> 
> 脚本下个版本将引用v2版的文档
> 
> 感谢你的付出

手动部署的吗，话说我的base链接没有加v2，不过你自己加了好像，我要不要改个名

**Comment by mengzonefire** [comment]
> > 部署完成: https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc-v2
> > 脚本下个版本将引用v2版的文档
> > 感谢你的付出
> 
> 手动部署的吗，话说我的base链接没有加v2，不过你自己加了好像，我要不要改个名

是, 手动同步仓库进行部署的, 你那的base可改可不改
