### ISSUE TITLE
关于更新最新版后出现的问题

### ISSUE THREAD

**Issue by shenqimolisha** [mengzonefire/rapid-upload-userscript#11]
大佬你好，是这样的。这次的最新脚本更新后，进去百度网盘页面只看到了更新公告并没有看到可以转存秒传的按钮和选项，然后，百度网盘页面好像是做了新的，目前点击“回到旧版”还可以看到秒传链接的选项，可以正常转存。正如你所说的，可能是新的页面接口不支持这个脚本吧。除此之外就没啥问题了。

**Comment by mengzonefire** [comment]
edge浏览器 tampermonkey4.16 脚本2.2.7版本, 刚测试了 按钮完全正常显示, 请反馈下使用的浏览器和油猴版本, 以及按F12截图控制台console的报错

**Comment by shenqimolisha** [comment]
> edge浏览器 tampermonkey4.16 脚本2.2.7版本, 刚测试了 按钮完全正常显示, 请反馈下使用的浏览器和油猴版本, 以及按F12截图控制台console的报错

我的edge浏览器 tampermonkey4.16 脚本2.2.7版本 没有显示出按钮。
谷歌浏览器 油猴4.13版本，脚本2.2.7版本，没有显示出按钮跟edge一样的问题，只有百度网盘页面的回到旧版才能看到转存按钮

**Comment by shenqimolisha** [comment]
![image](https://user-images.githubusercontent.com/93420332/169949487-45421503-74fd-4c25-aa7b-29e56ac4e22f.png)

**Comment by shenqimolisha** [comment]
![image](https://user-images.githubusercontent.com/93420332/169949541-f245ba09-cd1d-4b4b-a521-83e5670fa136.png)

**Comment by shenqimolisha** [comment]
![image](https://user-images.githubusercontent.com/93420332/169950055-dee90a27-e099-4d4d-8edd-286eec59225f.png)
这是谷歌的

**Comment by shenqimolisha** [comment]
![image](https://user-images.githubusercontent.com/93420332/169950233-8e40383c-1232-4716-ae82-7b975e6c55be.png)
这是谷歌浏览器的console

**Comment by shenqimolisha** [comment]
![image](https://user-images.githubusercontent.com/93420332/169950490-9daae49b-2112-486c-8410-49ccc725f21a.png)
这是旧版的百度网盘页面的控制台，这个可以正常转存，貌似问题跟新版的都是一样的。

**Comment by shenqimolisha** [comment]
![image](https://user-images.githubusercontent.com/93420332/169950663-26f6dd21-156c-415f-9cbe-24c086de8afa.png)
这个是edge浏览器 油猴4.16版 脚本2.2.7版本的旧版百度网盘页面的console截图

**Comment by shenqimolisha** [comment]
貌似跟版本没太大关系，反正还能用，就是不太适合用新页面，也不知道百度网盘这个新页面是什么时候弄的。。。

**Comment by mengzonefire** [comment]
新版页面早之前脚本就已经支持了, 效果如下图, 你那里我认为是和别的插件或脚本冲突了, 尝试关闭广告拦截类的插件或脚本试试

![](https://pic.rmb.bdstatic.com/bjh/9ed171bddecde252bff90efeb43729d8.png)

**Comment by mengzonefire** [comment]
确定了, 在你的截图中我发现整个顶部工具栏都消失了(1图), 导致脚本添加不上按钮, 关闭广告拦截插件就可以了, 正常的新版页面如2图所示:

![](https://pic.rmb.bdstatic.com/bjh/2c8a4cf336a9d62e7c5c0e7518debe88.png)
![](https://pic.rmb.bdstatic.com/bjh/de5d68603bc7e1dd59a6677d022ed176.png)

**Comment by shenqimolisha** [comment]
> 确定了, 在你的截图中我发现整个顶部工具栏都消失了(1图), 导致脚本添加不上按钮, 关闭广告拦截插件就可以了, 正常的新版页面如2图所示:
> 
> ![](https://pic.rmb.bdstatic.com/bjh/2c8a4cf336a9d62e7c5c0e7518debe88.png)
> ![](https://pic.rmb.bdstatic.com/bjh/de5d68603bc7e1dd59a6677d022ed176.png)

但是我把广告拦截的那个插件删除还是显示不出来。奇怪，我谷歌今天是第一次安装的，用的油猴插件是按照大佬你的安装说明里下的蓝奏云然后开发模式解压安装包程序的。也就是4.13根本不可能有广告拦截插件的啊，这个跟油猴版本有关吗？

**Comment by shenqimolisha** [comment]
> 确定了, 在你的截图中我发现整个顶部工具栏都消失了(1图), 导致脚本添加不上按钮, 关闭广告拦截插件就可以了, 正常的新版页面如2图所示:
> 
> ![](https://pic.rmb.bdstatic.com/bjh/2c8a4cf336a9d62e7c5c0e7518debe88.png)
> ![](https://pic.rmb.bdstatic.com/bjh/de5d68603bc7e1dd59a6677d022ed176.png)

还是不行，我把油猴版本更新到4.16.1，重新安装了下脚本2.2.7还是显示不出来。我看说跟dns有关系我就改了，结果好像没多大用。反而发现个有趣的现象，可能是我的谷歌访问慢(pan.baidu.com进去一开始是能看到后面的两个秒传按钮的，紧接着大概过了3s自动页面刷新就直接刷没了，给我整不会了，再刷新还是这样。)(我想我这个可能很特殊，估计得拼手速(笑)不然还没反应过来直接页面刷新刷没了。回到旧版但还是能正常用，那就这样吧，我也不想捣鼓了

**Comment by mengzonefire** [comment]
怎么还会自动刷新的, 完全无法复现问题, 我理解就是和其他脚本或插件冲突了, 尝试在插件管理页 和 油猴管理页卸载其他插件和脚本试试

**Comment by shenqimolisha** [comment]
> 怎么还会自动刷新的, 完全无法复现问题, 我理解就是和其他脚本或插件冲突了, 尝试在插件管理页 和 油猴管理页卸载其他插件和脚本试试

没啊。我谷歌除了油猴就没安装其他插件了。自动刷新那个感觉不稳定，刚才edge浏览器也出现了这个情况。edge是打开后是你截图的那样，但是一刷新或者点击“回到旧版”再点回来就没有了。
一开始一瞬间是能看到哪两个按钮的，但是很快就刷掉了，哎，我也不知道咋搞了。

**Comment by Wabbit4197** [comment]
我也有同样的问题 刚进入百度盘有显示秒传 但一瞬间俩个秒传的按钮就不见了 网页刷新后也是一样 俩个按钮闪一下就没了  我已经关闭adblock但没有效果   chrome和edge都不行

**Comment by mengzonefire** [comment]
脚本2.3.0版本应该已修复该问题, 请尝试更新

**Comment by shenqimolisha** [comment]
> 脚本2.3.0版本应该已修复该问题, 请尝试更新

嗯，好的。辛苦大佬了

**Comment by shenqimolisha** [comment]
> 脚本2.3.0版本应该已修复该问题, 请尝试更新

还是没有反应，只能回到旧版才能看到一个秒传按钮。edge和谷歌都是这样。

**Comment by Utsuho6** [comment]
把插件代码里的这行 var htmlTagNew = "div.nd-file-list-toolbar__actions"; // 新版界面秒传按钮的html父对象
替换成 var htmlTagNew = "div.wp-disk-header__center"; // 新版界面秒传按钮的html父对象
应该就能在百度网盘logo边上显示出来了 不改的话就和上面是一样的问题

**Comment by mengzonefire** [comment]
> 把插件代码里的这行 var htmlTagNew = "div.nd-file-list-toolbar__actions"; // 新版界面秒传按钮的html父对象 替换成 var htmlTagNew = "div.wp-disk-header__center"; // 新版界面秒传按钮的html父对象 应该就能在百度网盘logo边上显示出来了 不改的话就和上面是一样的问题

知道怎么回事了, 新版页面的dom结构更新了, 只不过有些人更了有些人没更, 我稍后修一下

**Comment by shenqimolisha** [comment]
> 把插件代码里的这行 var htmlTagNew = "div.nd-file-list-toolbar__actions"; // 新版界面秒传按钮的html父对象
> 替换成 var htmlTagNew = "div.wp-disk-header__center"; // 新版界面秒传按钮的html父对象
> 应该就能在百度网盘logo边上显示出来了 不改的话就和上面是一样的问题

我之前隐隐约约猜测是不是这么回事，dom结构，原来是这样啊。这就是为什么回到旧版可以用而新版显示不出来的原因吧

**Comment by shenqimolisha** [comment]
> 把插件代码里的这行 var htmlTagNew = "div.nd-file-list-toolbar__actions"; // 新版界面秒传按钮的html父对象
> 替换成 var htmlTagNew = "div.wp-disk-header__center"; // 新版界面秒传按钮的html父对象
> 应该就能在百度网盘logo边上显示出来了 不改的话就和上面是一样的问题

改了还是没变。放弃治疗了😂😂

**Comment by Utsuho6** [comment]
你改了之后有没有保存啊

**Comment by shenqimolisha** [comment]
> 你改了之后有没有保存啊
> 

保存了，那个reload点击后显示成功，点了保存没反应来着

**Comment by mengzonefire** [comment]
不急, 等我debug

**Comment by shenqimolisha** [comment]
> 把插件代码里的这行 var htmlTagNew = "div.nd-file-list-toolbar__actions"; // 新版界面秒传按钮的html父对象 替换成 var htmlTagNew = "div.wp-disk-header__center"; // 新版界面秒传按钮的html父对象 应该就能在百度网盘logo边上显示出来了 不改的话就和上面是一样的问题

![image](https://user-images.githubusercontent.com/93420332/170243750-f5420543-712d-48d3-a896-2ec2c1e0a00f.png)
很神奇，跑上面去了，可能位置还得修改下？

**Comment by Utsuho6** [comment]
没问题改了之后就是在那 改到别的div位置更怪

**Comment by mengzonefire** [comment]
2.3.2版本, 已经修复了按钮不显示的问题

结论:
度盘这次更新更改了元素的类名, 而且会先加载一次旧代码, 然后再加载更新代码, 导致脚本按钮添加上又被覆盖掉, 同时转存和生成功能也无法正常使用, 而且, 貌似是在做灰度测试, 有些地区更新了, 有些地区没更新

现在姑且是加上了两种类名的兼容以及轮询添加按钮
