### ISSUE TITLE
更新日志有好多版本，哪一个才是主要的

### ISSUE THREAD

**Issue by XTsat** [mengzonefire/rapid-upload-userscript#13]
[以前版本的主页更新日志](https://github.com/mengzonefire/rapid-upload-userscript/blob/e55af76651a473cb33b47674a09827ddc0c2b12a/homePage.md#%E6%9B%B4%E6%96%B0%E8%AF%B4%E6%98%8E)

[脚本更新弹出的更新日志](https://github.com/mengzonefire/rapid-upload-userscript/blob/main/src/components/updateInfo.html)

[Greasy Fork的更新日志](https://greasyfork.org/zh-CN/scripts/424574-%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96/versions)

这三个版本日志都互相有差异，特别是之前脚本主页和弹出的更新日志为什么也不一样

现在这三个更新日志以哪个为主比较好，我现在推了一个有三版本的[文档](https://xtsat.github.io/rapid-upload-userscript-doc/development/%E8%84%9A%E6%9C%AC%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97.html)

**Comment by mengzonefire** [comment]
"主页更新日志" -> 完全冗余, 没啥用

"弹窗更新日志" 与 "gf更新日志" 互补

"弹窗更新日志" 主要是功能上的更新, "gf更新日志" 则基本作为commit信息使用, 确实挺杂乱的, 尤其早期, 基本是乱写的

**Comment by XTsat** [comment]
主页的确实没用，反正安装都是安装最新的版本，日志没用，而且现在主页更新日志也已经删了

我觉得显示最近几个版本和日期都算够了，而且我觉得网盘弹窗那个尺寸也不适合看更新消息，也不好滚动

**Comment by mengzonefire** [comment]
这里是旧版本的gf更新日志: [web.archive.org](https://web.archive.org/web/20210329213419/https://greasyfork.org/zh-CN/scripts/397324-%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96/versions)

我打算的方案如下, 文档页保留 "脚本更新说明" 和 "历史版本一览", 然后脚本更新弹窗仅显示当前版本更新信息, 并引用文档页的  "脚本更新说明" 

然后是gf更新日志有部分以前漏填的, 我等下补充到文档页

**Comment by XTsat** [comment]
> 这里是旧版本的gf更新日志: [web.archive.org](https://web.archive.org/web/20210329213419/https://greasyfork.org/zh-CN/scripts/397324-%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96/versions)
> 
> 我打算的方案如下, 文档页保留 "脚本更新说明" 和 "历史版本一览", 然后脚本更新弹窗仅显示当前版本更新信息, 并引用文档页的 "脚本更新说明"

这里说的 "脚本更新说明" 是指 `components/updateInfo.html` 对吧，而不是已经删除更新说明的 `HomePage.md`

**Comment by mengzonefire** [comment]
> > 这里是旧版本的gf更新日志: [web.archive.org](https://web.archive.org/web/20210329213419/https://greasyfork.org/zh-CN/scripts/397324-%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96/versions)
> > 我打算的方案如下, 文档页保留 "脚本更新说明" 和 "历史版本一览", 然后脚本更新弹窗仅显示当前版本更新信息, 并引用文档页的 "脚本更新说明"
> 
> 这里说的 "脚本更新说明" 是指 `components/updateInfo.html` 对吧，而不是已经删除更新说明的 `HomePage.md`

是的, HomePage.md内的更新信息可以直接废弃了, HomePage.md文件仅是作为gf介绍页的一个backup, 没有太大意义

**Comment by mengzonefire** [comment]
updateInfo.html的内容也有问题, 掺了不少没必要的进去, 我等下在文档页做下删减只保留功能性更新, 然后脚本下版本updateInfo.html仅保留当前版本信息+文档页历史更新引用

不然实在是太乱了

# TODO备忘
1. [脚本更新说明](https://xtsat.github.io/rapid-upload-userscript-doc/development/%E8%84%9A%E6%9C%AC%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97.html) 做删减, 删除非功能性更新, 通知类信息转移到 [文档通知页](https://xtsat.github.io/rapid-upload-userscript-doc/development/%E9%80%9A%E7%9F%A5.html)
2. [历史版本一览](https://xtsat.github.io/rapid-upload-userscript-doc/development/%E5%8E%86%E5%8F%B2%E7%89%88%E6%9C%AC.html) 做补齐

**Comment by XTsat** [comment]
> 通知类信息转移到 [文档通知页](https://xtsat.github.io/rapid-upload-userscript-doc/development/%E9%80%9A%E7%9F%A5.html)

通知页我之前把他隐藏了，因为我感觉过时的通知没有什么用，如果要通知什么加在主页上显示出来比较好，通知文档就作为一个留档

现在 `HomePage.md` 里面的通知不是也把历史通知删了吗，只留了几个还有用的

>[历史版本一览](https://xtsat.github.io/rapid-upload-userscript-doc/development/%E5%8E%86%E5%8F%B2%E7%89%88%E6%9C%AC.html) 做补齐

Greasy Fork 的老版本我已经加进去了，为啥GF要删老版本的历史记录，还得看快照，~~你等下看看有没有错了的地方~~
