### ISSUE TITLE
能否将秒传页面优化为树状图呢

### ISSUE THREAD

**Issue by XTsat** [mengzonefire/rapid-upload-userscript#14]
类似于github这种

并且将失败后的表现形式优化一下,将每种错误的原因分开放置

我简单P了一下

![画板 1](https://user-images.githubusercontent.com/44708609/180637591-ebbdda89-2ca8-4701-a18f-62ec3a94bba6.png)

还有现有的报错参考是两个载点1

我觉得可以适当的扩宽显示窗口，让显示出来的效果更清晰

**Comment by mengzonefire** [comment]
雀食, 而且看样子CSS样式也需要优化, 我有空研究下

不过我设计相当苦手, 想不出来啥好的面板样式, 能有个成品例图给我参考最好

**Comment by XTsat** [comment]
你在原 reply 上编辑的没有发邮件，我之前都没看到，脚本文档载点1好像炸了

**Comment by mengzonefire** [comment]
> 你在原 reply 上编辑的没有发邮件，我之前都没看到，脚本文档载点1好像炸了

阿, 是我更新不小心把路径配置覆盖回去了, 我修正下

**Comment by XTsat** [comment]
忘了修改base了是吧，可以把原来的文档换个base，或者我换个仓库名字也可以

**Comment by mengzonefire** [comment]
> 忘了修改base了是吧，可以把原来的文档换个base，或者我换个仓库名字也可以

可以, 那就改成v2吧, 我下版本把脚本内的引用也修正下

代码内需要修正的应该就这两处地方

base: '/rapid-upload-userscript-doc/',

href="/rapid-upload-userscript-doc/

**Comment by XTsat** [comment]
我原始仓库没有需要改的地方吧，我看了下我的都是直接base指向GitHub，唯一有v2的是更新记录和作者页的载点12

**Comment by mengzonefire** [comment]
因为我的那个载点还部署着旧版的文档rapid-upload-userscript-doc, 直接覆盖掉会导致旧脚本的文档跳转不可用

不改放着也可以, 我每次同步只需要修改两处地方, 不算麻烦

**Comment by XTsat** [comment]
替换掉旧版文档旧版脚本应该也能直接进新的文档吧，而且脚本不更新一般也不用了吧，毕竟旧版可用性低，好几次的cdn更换了

**Comment by mengzonefire** [comment]
> 替换掉旧版文档旧版脚本应该也能直接进新的文档吧，而且脚本不更新一般也不用了吧，毕竟旧版可用性低，好几次的cdn更换了

并不行, 旧版文档的路径配置和新版不一样, 引用不兼容, 文档暂时就这样吧

**Comment by XTsat** [comment]
主要是我重新改动了文档结构是吧，所以错误代码的位置不一样了的这种不一样吗

应该是只有主页是正常的，其他文档的链接都会报错是不是

但是报错了404也能直接回到主页吧，主页也放了错误链接的按钮

就拿原本的报错链接举例

![Snipaste_2022-07-28_01-19-18](https://user-images.githubusercontent.com/44708609/181309600-8c957f65-694d-4443-b5f1-9f4bd5ecb721.png)

**Comment by mengzonefire** [comment]
> 替换掉旧版文档旧版脚本应该也能直接进新的文档吧，而且脚本不更新一般也不用了吧，毕竟旧版可用性低，好几次的cdn更换了

折腾了一下, 解决了, 整了手骚操作, 效果如下:

https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc/generate-bdcode/

https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc/document/Info/%E8%84%9A%E6%9C%AC%E8%AF%B4%E6%98%8E.html

**Comment by XTsat** [comment]
把旧版的dist合到一起解析吗

**Comment by mengzonefire** [comment]
柿阿柿阿，我看了下dist里面反正除了index和404就没有其他冲突了，直接合并算了

**Comment by mengzonefire** [comment]
脚本2.3.8版本新增了一个 "极速生成" 功能

~~启用后即可极大幅度提升生成秒传的体验, 应该不太可能再生成失败了~~

~~所以列表优化就饶了我吧, 暂时没啥精力研究了~~

后续测试出现太多问题, 又废弃掉了, 还是继续优化列表吧

**Comment by mengzonefire** [comment]
2.4.6版本, 姑且是做了下嵌套, 大概是够用了, 至于样式美化就以后再说吧...
![Snipaste_2022-11-11_01-54-55](https://user-images.githubusercontent.com/44224240/201179279-77ae11c4-e943-4a42-b419-13892f260a1c.png)
