### ISSUE TITLE
【选中文件夹生成秒链时】失败原因：请求错误(尝试使用最新版Chrome浏览器/更新油猴插件)(#400)

### ISSUE THREAD

**Issue by zmo6** [mengzonefire/rapid-upload-userscript#16]
失败原因：请求错误(尝试使用最新版Chrome浏览器/更新油猴插件)(#400)
系统：win10
浏览器：chrome  版本 104.0.5112.102（正式版本） （64 位）
Tampermonkey: v4.16.1
秒传链接提取插件版本：2.3.7
问题描述：选中文件生成秒链一切正常，当选中文件夹生成秒链时就会生成失败,失败原因：请求错误(尝试使用最新版Chrome浏览器/更新油猴插件)(#400)

换用edge浏览器也是一样的结果

**Comment by mengzonefire** [comment]
使用相同环境测试未能复现, 请尝试:
1. 改用 暴力猴 或 Tampermonkey beta 版插件
2. 关闭网络代理工具

**Comment by zmo6** [comment]
感谢！已查出可能的原因了。更换各种浏览器与脚本管理器（无代理）都无法获取整个文件夹秒链，只能选中文件生成秒链。

后面无意间换了个云盘账号发现可以选中文件夹获取里面文件的秒链了。经对比，**之前的账号为扩容盘**，后经测试未扩容的账号一切正常

**Comment by mengzonefire** [comment]
> 感谢！已查出可能的原因了。更换各种浏览器与脚本管理器（无代理）都无法获取整个文件夹秒链，只能选中文件生成秒链。
> 
> 后面无意间换了个云盘账号发现可以选中文件夹获取里面文件的秒链了。经对比，**之前的账号为扩容盘**，后经测试未扩容的账号一切正常

原来如此，感谢反馈，下次更新会把这个情况加到文档说明里
