### ISSUE TITLE
[生成秒传链接报错#请求错误#报错BUG?]

### ISSUE THREAD

**Issue by KitoCedon** [mengzonefire/rapid-upload-userscript#17]
Edge版本 107.0.1418.42 (正式版本) (64 位)
Tampermonkey V4.16.1
秒传V2.4.6

在按照issues#16的做法换了个网盘账号后发现md5报错(因IDM)
关闭IDM后成功用新账号生成
再换回原账号发现能够生成链接，且没有报错
可能是个报错小BUG

**Comment by mengzonefire** [comment]
我需要完整稳定的复现过程才能debug, 以及我没有扩容号用于测试, 需要我修的话请提供:

1. 完整复现过程

2. 一个扩容号账号(只需要cookie里的bduss即可), 发送到邮箱 mengzonefire@outlook.com

如果复现过程不稳定直接理解为百度服务端问题, 在下无能为力

**Comment by KitoCedon** [comment]
BDUSS


HBoSzJTb1dVU05tbFhWcU0xY1FaZDlLNkp-RnBkd3hGZFoyd3VMRkNrRGF6SlpqSUFBQUFBJCQAAAAAAAAAAAEAAACUuZZ4Q2Vkb262r8L-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANo~b2PaP29jW





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengzonefire/rapid-upload-userscript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月12日(星期六) 上午9:19
***@***.***&gt;;
抄送:&nbsp;"Rinne と ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mengzonefire/rapid-upload-userscript] [生成秒传链接报错#请求错误#报错BUG?] (Issue #17)





 
我需要完整稳定的复现过程才能debug, 以及我没有扩容号用于测试, 需要我修的话请提供:
  
 
完整复现过程
 
 
 
一个扩容号账号(只需要cookie里的bduss即可), 发送到邮箱 ***@***.***

**Comment by KitoCedon** [comment]
0. 发的账号就是报错账号


1. 脚本安装完后刷新 云网页端 尝试生成 文件夹/文件 链接

2. 生成失败报错#请求错误, 重启浏览器以及重新登录账号仍报错#请求错误, 但可以使用网页版秒传的生成方式

3. 尝试换个账号生成(我现建现试的), 报错#MD5, 关闭IDM后生成成功

4. 切换回原账号尝试生成链接,成功

5. 之后无法复现


6.可能为第一步问题或服务端问题
