### ISSUE TITLE
87e5da6133e9d5cef5a5b80d0b168e9c#860c896ca7a6c904f4a0c64b30cd579a#378703968#序.7z

### ISSUE THREAD

**Issue by anplux** [mengzonefire/rapid-upload-userscript#19]

**Comment by mengzonefire** [comment]
![Snipaste_2023-01-06_07-10-48](https://user-images.githubusercontent.com/44224240/210897627-287b1ff5-72a0-4d6c-9eb0-522f5a751b2c.png)
