### ISSUE TITLE
【BUG/建议】石墨文档升级

### ISSUE THREAD

**Issue by tasty0tomato** [mengzonefire/rapid-upload-userscript#2]
优先级：**中**
目前，该项目的文档全部保存在石墨文档，但现在石墨文档处于升级状态，无法查看文档，如果在此期间想查看文档就会陷入苦难。建议的话，可以把文档直接写到项目里面，甚至放到GitHub上的Wiki也可以。

**Comment by mengzonefire** [comment]
1. 经测试, 文档全部可以正常访问, 查看公告也是说升级不影响已开启分享的文档,, 不知道你是访问哪篇文档, 以及遇到了哪种问题.
2. 会在下个版本添加一个备用文档载点, 并把文档备份到github, 这个问题就算解决.
![截图](https://pic.rmb.bdstatic.com/bjh/f8277e9a4ffbc35ad8a1b47831f65ab1.png)

**Comment by tasty0tomato** [comment]
@mengzonefire  比如这个 https://shimo.im/docs/Jqf8y260KuofSb4K/

**Comment by mengzonefire** [comment]
如图, 未登录正常访问, 无法访问的话有可能是地区问题
![截图](https://pic.rmb.bdstatic.com/bjh/d2dc8fa39fc2c6b53102f1ffbb4c8d87.png)

**Comment by tasty0tomato** [comment]
![image](https://user-images.githubusercontent.com/48764449/133922679-d1532be9-8d48-4d05-99fc-e5b6614c9d62.png)

**Comment by mengzonefire** [comment]
已将文档备份到github: https://github.com/mengzonefire/rapid-upload-userscript/tree/main/doc
