### ISSUE TITLE
可以支持一下转换成pandown的吗

### ISSUE THREAD

**Issue by Smile8848** [mengzonefire/rapid-upload-userscript#20]
最新的好像都没法转

**Comment by mengzonefire** [comment]
不行的, 最新版默认开启极速生成, 极速生成得到的简化版秒传需要使用新版秒传接口, 与pandown不兼容

你在脚本的设置页(秒传框输入set)关闭 "极速生成" 就能 生成原版秒传了, 原版秒传就能正常转换成pandown

秒传格式转换工具:  https://mengzonefire.code.misakanet.cn/baidupan-rapidupload/convert.html

**Comment by Smile8848** [comment]
> 不行的, 最新版默认开启极速生成, 极速生成得到的简化版秒传需要使用新版秒传接口, 与pandown不兼容
> 
> 你在脚本的设置页(秒传框输入set)关闭 "极速生成" 就能 生成原版秒传了, 原版秒传就能正常转换成pandown
> 
> 秒传格式转换工具: https://mengzonefire.code.misakanet.cn/baidupan-rapidupload/convert.html

好吧。。。
