### ISSUE TITLE
建议区分相对路径和绝对路径

### ISSUE THREAD

**Issue by qianbinbin** [mengzonefire/rapid-upload-userscript#21]
- 相对路径：`foo/bar`，此时如果“保存路径”不为空，则保存到该路径，否则保存到**当前路径**。
- 绝对路径：`/foo/bar`，此时如果“保存路径”不为空，则保存到该路径，否则保存到网盘**根目录**。或者完全忽略“保存路径”的内容，总是保存到根目录。

目前的处理方式是 `foo/bar` 和 `/foo/bar` 没有任何区别，个人认为不太符合直觉？

**Comment by qianbinbin** [comment]
另外，目前生成秒传时默认是绝对路径，也不符合直觉

**Comment by mengzonefire** [comment]
个人认为网页脚本的实现原则与桌面工具不同, 个人考虑网页脚本优先保证用户能第一时间看到文件, 目前统一视为相对路径已经实现此原则(单次转存根目录统一), 类似PCS-GO客户端的 "工作路径" 实现

1. 保存路径为空转存到 (当前路径 + 文件路径), 转存完成后调用列表刷新方法 -> 立即看见所有转存的文件
2. 保存路径不为空转存到 (保存路径 + 文件路径), 转存完成后提供"打开目录"按钮跳转到保存路径 -> 立即看见所有转存的文件

而严谨实现绝对路径则会导致出现多个根目录的情况, 就要到处去翻文件了

生成秒传的导出路径会在下版本优化为相对路径, 目前不仅不符合直觉, 还导致导出的路径过长

**Comment by qianbinbin** [comment]
是的，直接统一成相对路径也可以，以根目录开头很奇怪。
另外，文件开头 256K 的 md5 似乎没有什么作用，为什么不直接去掉呢？为了文件的快速检验？

**Comment by mengzonefire** [comment]
> 是的，直接统一成相对路径也可以，以根目录开头很奇怪。 另外，文件开头 256K 的 md5 似乎没有什么作用，为什么不直接去掉呢？为了文件的快速检验？

根目录开头会在下次更新时优化掉(生成为foo/bar),  文件开头256K的md5用于兼容旧接口:

1. https://pcs.baidu.com/rest/2.0/pcs/file?app_id=266719&method=rapidupload&ondup=overwrite&content-length={}&content-md5={}&slice-md5={}&path={}
2. https://pan.baidu.com/api/rapidupload

目前脚本统一使用新接口(https://pan.baidu.com/rest/2.0/xpan/file?method=create) 所以不需要了, 但其他转存工具基本都还停留在旧接口, 在脚本的设置页中打开 "极速生成" 即可忽略smd5(v2.5.3开始默认开启)

**Comment by qianbinbin** [comment]
好的，谢谢解答，您可以随时关闭这个 issue
