### ISSUE TITLE
关于秒传脚本的安全性问题

### ISSUE THREAD

**Issue by zhbzxf** [mengzonefire/rapid-upload-userscript#23]
作者您好，请问使用秒传脚本是否有安全风险（如被百度封号等）？

另外，此脚本是否涉及账号密码等？

抱歉，没有查到安全性说明，可否说明一下？

个人习惯，比较在意安全问题，请您原谅

最后，谢谢作者，脚本用着很方便

**Comment by mengzonefire** [comment]
你提到的所有问题均由于我个人能力所限, 没法给出专业的答复, 建议是另请高明

工具源码均已给出, 可自行审查

**Comment by zhbzxf** [comment]
好的，谢谢，明白了

不过我不是搞计算机的，可否简单说明一下:)

**Comment by mengzonefire** [comment]
> 不过我不是搞计算机的，可否简单说明一下:)

不可以，我也不是搞计算机的（脚本是我乱写的，请去找搞计算机的人问
