### ISSUE TITLE
[Feature Request] 一般链接支持

### ISSUE THREAD

**Issue by endless7** [mengzonefire/rapid-upload-userscript#24]
作者您好，我有时候需要把普通链接批量导入到网盘/秒传非秒传混合导入，能否对此进行支持捏，感谢！
eg：`https://pan.baidu.com/s/1IXEOhxxxxXra4UShTmU69A?pwd=nqxh`

**Comment by mengzonefire** [comment]
[BaiduPCS-Go](https://github.com/qjfoidnh/BaiduPCS-Go) 已实现你的需求:

## 转存文件/目录
```
# 转存分享链接里的文件到当前目录:
BaiduPCS-Go transfer <分享链接> <提取码>
# 转存通用秒传链接里的文件到当前目录:
BaiduPCS-Go transfer <秒传链接>
```

**Comment by endless7** [comment]
Thanks!!
