### ISSUE TITLE
关于从服务器获取到的md5到脚本生成的秒传md5的转换函数

### ISSUE THREAD

**Issue by infchaos** [mengzonefire/rapid-upload-userscript#25]
我最近发现服务器返回的md5加上size加上文件名就能拼凑出秒传链接，但是个别会失败，我于是看了源码，看到了decryptMd5函数，它会根据某一位的字符是否是16进制字符来判断要不要对这个md5解密，加上这个函数后解密是解密了但是仍然有一部分秒传失败，但是用脚本生成的能成功，经过观察发现用服务器返回的md5扔进decryptMd5函数算出来的值跟脚本生成的值不一定对得上，所以我想询问这个脚本是如何解密md5的？有什么坑吗？

**Comment by mengzonefire** [comment]
meta接口的md5有概率错误（无论是否加密），下载接口dlink的header内的content md5百分百正确，以上
