### ISSUE TITLE
(#9019):

### ISSUE THREAD

**Issue by nilfunc** [mengzonefire/rapid-upload-userscript#27]

**Comment by mengzonefire** [comment]
https://greasyfork.org/zh-CN/scripts/424574

2.6.4版本已修复

**Comment by nilfunc** [comment]
谢谢

**Comment by nilfunc** [comment]
网页版工具能修一下嘛

**Comment by mengzonefire** [comment]
> 网页版工具能修一下嘛

已经修了

https://mengzonefire.code.misakanet.cn/baidupan-rapidupload

https://mengzonefire.github.io/baidupan-rapidupload
