### ISSUE TITLE
错误代码#514

### ISSUE THREAD

**Issue by Pengyoushiyige** [mengzonefire/rapid-upload-userscript#28]
[秒传链接提取 by mengzonefire]:样式包加载失败,请前往脚本页反馈:https://greasyfork.org/zh-CN/scripts/424574 错误代码:#514

**Comment by mengzonefire** [comment]
未能复现，请反馈下使用的油猴插件版本和脚本版本，#514是请求被拦截了，可能跟系统环境有关，若无法解决可以尝试重置一下脚本, 脚本2.6.6版本默认使用内置样式包，不会出现此问题(不修改脚本的主题设置)

**Comment by Pengyoushiyige** [comment]
我尝试过好多次重新安装脚本但是没有用 我用的油猴插件的版本是4.18.1，秒传链接提脚本的版本是2.6.6

**Comment by Pengyoushiyige** [comment]
请告诉我如何重置脚本吧 我怀疑每次重新安装后都是按照原来的设置（修改了外观主题） 所以才无法正确使用的

**Comment by mengzonefire** [comment]
> 请告诉我如何重置脚本吧 我怀疑每次重新安装后都是按照原来的设置（修改了外观主题） 所以才无法正确使用的

重新安装不会清除脚本的本地数据(设置项), 需要删除脚本，清空回收站，再安装脚本才会清除(或重置脚本)

若切换主题还是报错514的话, 在扩展管理页勾选开发者模式，进入油猴的background.html;(背景页)的控制台console界面查看对应的报错，自行排查问题 (我自己使用 4.18.1+2.6.6测试并未复现此问题)

![Snipaste_2023-03-26_19-35-36](https://user-images.githubusercontent.com/44224240/227773002-a06b7394-8f6f-468d-a757-5d568c019b40.png)
