### ISSUE TITLE
#404转传失败

### ISSUE THREAD

**Issue by Vergil911** [mengzonefire/rapid-upload-userscript#29]
今天(2023/4/25)使用时发现转存失败，于是更新至2.7.5，仍然失败。目标资源的生成日期时3/31,尝试了好几个不同的资源，都是失败并显示同样的失败代码#404

**Comment by mengzonefire** [comment]
2.7.3版本已修复此问题

**Comment by Vergil911** [comment]
> 

所以是要卸载2.7.5然后重新安装2.7.3吗？

**Comment by mengzonefire** [comment]
> 所以是要卸载2.7.5然后重新安装2.7.3吗？

没有2.7.5版本吧，2.7.5可能是别人的（不知道你哪下的，卸载重装即可

**Comment by Vergil911** [comment]
> > 所以是要卸载2.7.5然后重新安装2.7.3吗？
> 
> 没有2.7.5版本吧，2.7.5可能是别人的（不知道你哪下的，卸载重装即可

好的，已卸载更新，现在测试正常了，谢谢！
