### ISSUE TITLE
文件名中包含路径字符"\"导致转存失败，但实际成功的问题

### ISSUE THREAD

**Issue by GenesisAN** [mengzonefire/rapid-upload-userscript#3]
例：
#\MOD包\20-11-20.z36
秒传码最后的#后面接文件名称，而如果要让文件存存在目录结构关系就需要加 ``\ ``字符分隔
但这样会因为``\``的存在，导致过路径校验时失败，并提示：链接内的文件路径错误

而实际这时候，文件已经转存成功，并且目录关系也存在。

望修复

**Comment by mengzonefire** [comment]
正确的格式为: #/MOD包/20-11-20.z36
路径分隔符 \ 仅用于win平台的绝对路径, 在百度网盘(linux服务端)路径中则为非法字符
另附: 路径校验失败将不会继续执行转存操作, 参考 [rapiduploadTask.tsx](https://github.com/mengzonefire/rapid-upload-userscript/blob/main/src/baidu/common/rapiduploadTask.tsx) -> line47
