### ISSUE TITLE
油叉的秒传脚本没了,现在搜不到

### ISSUE THREAD

**Issue by ily520** [mengzonefire/rapid-upload-userscript#30]

**Comment by ily520** [comment]
打开脚本页显示已经被删了

**Comment by eoirwt** [comment]
@mengzonefire 大佬，妙传的油猴脚本主页被删了...

**Comment by himetuki** [comment]
是这样

**Comment by himetuki** [comment]
是这样，被删了，而且没法用了

**Comment by hd80606b** [comment]
禁用更新就行了

**Comment by qrk158** [comment]
那油猴的还能等到重新上线么

**Comment by EndOfNewFall** [comment]
油叉的秒传脚本没了,你应该私信作者，该问题不该在issues上提出。如果你只是想使用，有成品代码：dist/秒传连接提取.user.js

**Comment by eoirwt** [comment]
> 油叉的秒传脚本没了,你应该私信作者，该问题不该在issues上提出。如果你只是想使用，有成品代码：dist/秒传连接提取.user.js

@ily520 这位大佬说的没错👍，你直接把成品代码cv到油猴再安装就行，可以把这个issues撤销了

**Comment by eoirwt** [comment]
> 油叉的秒传脚本没了,你应该私信作者，该问题不该在issues上提出。如果你只是想使用，有成品代码：dist/秒传连接提取.user.js

@ily520 这位大佬说的没错👍，你直接把成品代码cv到油猴再安装就行，该问题的确不该在issues上提出。

**Comment by XTsat** [comment]
[开发版本安装指南](https://xtsat.github.io/rapid-upload-userscript-doc/document/Install/About.html#%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC)

脚本指南页已加回开发版支持

``注意此分支为dev分支, 正式版可用时请不要使用此分支``

**Comment by xiaomuzi1987** [comment]
> 油叉的秒传脚本没了,你应该私信作者，该问题不该在issues上提出。如果你只是想使用，有成品代码：dist/秒传连接提取.user.js

请教下这个成品代码如何使用？
