### ISSUE TITLE
出现了奇怪的文件夹，“我的应用数据”。

### ISSUE THREAD

**Issue by knowonething** [mengzonefire/rapid-upload-userscript#31]
大佬，使用2.7.4脚本之后，今天发现网盘里面出现了“我的应用数据”这么个文件夹，里面还有个文件，“秒传生成的测试文件.mengzonefire”。文件能删除，文件夹删不掉，这是为什么？

**Comment by ONeresin** [comment]
这个文件夹好像是度盘的预置文件夹，无法删除的
