### ISSUE TITLE
插件被greasyfork下架了

### ISSUE THREAD

**Issue by ACGtutusang** [mengzonefire/rapid-upload-userscript#32]
不知道什么时候能重新上

**Comment by XTsat** [comment]
[开发版本安装指南](https://xtsat.github.io/rapid-upload-userscript-doc/document/Install/About.html#%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC)

脚本指南页已加回开发版支持

``注意此分支为dev分支, 正式版可用时请不要使用此分支``
