### ISSUE TITLE
脚本反复被Greasy Fork下架，dev分支可能还是得启用

### ISSUE THREAD

**Issue by XTsat** [mengzonefire/rapid-upload-userscript#33]
我觉得以后dev分支的dist以后要长期支持了，避免经常性的脚本下架

**Comment by XTsat** [comment]
之后我准备换个文档页主题，使用VuePress Theme Hope，顺带能支持评论和浏览量记录

**Comment by hoothin** [comment]
并不是"被"Greasy Fork下架，应该是作者自己下架的。
自从作者下架后有一帮傻逼疯狂夹带私货上传抄袭脚本，删也删不过来。
不知道作者为什么要下架，也许是被伸手党惹恼了吧。
