### ISSUE TITLE
会员秒传未生效404

### ISSUE THREAD

**Issue by jxl926** [mengzonefire/rapid-upload-userscript#35]
您好，反馈：2.7.8版本，有两个账号，一个度盘超级会员账号转存显示失败，秒传未生效#404。另一个非会员账号转存成功。不知道是不是会员的原因，也可能单纯不同账号的问题。

**Comment by tkx15816072342** [comment]
看到楼主这么说，我也测试了下我这里的情况。的确如此，1个会员号404，1个非会员号正常，看来是度盘服务器又出问题了。应该和脚本没什么关系。

**Comment by 1678334706** [comment]
并没有啊 我非会员也是无法保存啊 我都开代理了 跳到日本 美国节点 都没法保存

**Comment by tkx15816072342** [comment]
> 

说明无法保存的问题和会员与否没关系，目前应该是什么都没有的空白号转存成功概率更大些

**Comment by jxl926** [comment]
反馈：我非会员的号快存满了，并不是空白号，能转存

**Comment by Minions-zzw** [comment]
你好，我的秒传转存也是显示404，2.7.8版本，不知道怎么能解决

**Comment by Yuan-14** [comment]
反馈！我的会员账号同样出现该问题，但朋友的非会员空白号可以正常使用秒传

**Comment by ccyfd** [comment]
我试过申请一个小号之后秒传还是能用，自己的超级会员大号是无法使用的

**Comment by sim1233** [comment]
我也是404 以前下过的秒传 这几天在提取都是404

**Comment by liang1996718** [comment]
俺也一样  404  不知道咋回事

**Comment by star2056** [comment]
我的也是出现了转存失败的问题

**Comment by 1chang** [comment]
注意到以下情况：以pcs.baidu.com开头域名来进行转存操作，仍然可行。因此可能是脚本本身某个动作被block掉了。

**Comment by mp-s** [comment]
反馈：我的会员账号同样出现该问题，但朋友的非会员满存号可以正常使用秒传

**Comment by listenbass** [comment]
会员号404   非会员号没问题
会员转传失败会说 文件以删除无法转移
估计是会员号的秒传文件生成地址被block了?

**Comment by 291602972** [comment]
会员号404无法保存拿个新手机直接保存成功 草

**Comment by listenbass** [comment]
换手机怎么保存成功???用web版?
