### ISSUE TITLE
转载请求

### ISSUE THREAD

**Issue by lihengdao666** [mengzonefire/rapid-upload-userscript#6]
您好，我是油猴中文网的管理员李恒道，我想将您的脚本：秒传链接提取，转载至我们的论坛：https://bbs.tampermonkey.net.cn/

关于更新，我们会使用您的脚本链接设置自动同步在我们的论坛上进行更新。如果您不愿意创建账号，我们将会将转载的脚本放在一个脚本搬运工的账号上，未来如果您愿意来论坛玩耍将会把权限返还给您

期待大佬的回复^_^。

关于我们论坛是一个油猴脚本的开发与交流的社区；同时我们也提供脚本的发布和安装，另外我们有开发一个新的类油猴扩展：脚本猫，除了支持油猴脚本外，还支持后台与定时脚本，更多的功能和接口还在开发中。

**Comment by mengzonefire** [comment]
脚本使用gpl3协议开源, 遵循协议随意使用
