### ISSUE TITLE
百度网盘改版了

### ISSUE THREAD

**Issue by SuouAmane** [mengzonefire/rapid-upload-userscript#7]
百度网盘变成新版之后  跳转到保存的目录不好用了，不会跳转了

**Comment by mengzonefire** [comment]
已在2.1.3版本修复, 请前往更新

**Comment by SuouAmane** [comment]
现在就是2.1.3 好像并没有改变

**Comment by mengzonefire** [comment]
> 现在就是2.1.3 好像并没有改变

gf的cdn刷新需要时间, 现在点更新实际还是安装的2.1.2, 稍等一下再点更新

北京时间22:14, cdn已经刷新好了
