### ISSUE TITLE
能否取消输入秒传链接时的网页页面变暗效果？

### ISSUE THREAD

**Issue by wormshi** [mengzonefire/rapid-upload-userscript#8]
从输入到正式将资源转入网盘是一个很快的过程，网页因为输入框、提示框的反复出现而亮度反复变化，闪烁的屏幕光有害视力

**Comment by mengzonefire** [comment]
雀  食。

Add [TODO 1,2,3](https://github.com/mengzonefire/rapid-upload-userscript/blob/main/README.md#TODO)

**Comment by mengzonefire** [comment]
临时解决方案：输入框输入set->确定->更换为灰色主题

大概可以缓解

**Comment by mengzonefire** [comment]
屏闪问题已在2.2.0修复，可前往更新：

https://greasyfork.org/zh-CN/scripts/424574

由于取消弹窗时的背景变暗会影响视觉效果，故废弃
